name: Clean Github Workflow Artifacts

on:
    push:
        branches:
            - "main"
    workflow_dispatch:

jobs:
    delete-artifacts-and-cache:
        name: Delete Artifacts
        runs-on: ubuntu-latest
        permissions: write-all

        steps:
        - uses: jimschubert/delete-artifacts-action@v1
          with:
            log_level: 'debug'
            min_bytes: '0'
            active_duration: '30m'